.dockerignore
config/Shared/config_default-docker.php
config/Shared/config_default.php
config/install/docker.yml
src/Pyz/Yves/ShopUi/Theme/default/styles/basics/_typography.scss

202001.0-p1 B2B release
- Fixed ACL configuration for the HealthCheck services, so that ZED endpoint is now accessible for a not logged-in user.

202001.0-p1 release

---

composer.json
composer.lock
config/Shared/config_default-docker.production.php
deploy.spryker-b2bprodeu.yml
deploy.spryker-b2bprodus.yml

- Ticket: https://spryker.atlassian.net/browse/CC-14625

CC-14625: Enabled optimized settings for a staging environment.

---

composer.json
composer.lock
src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
src/Pyz/Zed/DocumentationGeneratorRestApi/DocumentationGeneratorRestApiConfig.php

Ticket: https://spryker.atlassian.net/browse/CC-16706

CC-16706: Added support for nested relationships in swagger documentation.

---

composer.lock

Bugfix integrations

---

composer.lock
src/Pyz/Yves/CustomerReorderWidget/CustomerReorderWidgetDependencyProvider.php

Ticket: https://spryker.atlassian.net/browse/CC-16667

Integrated reorder bugfix

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-16744

CC-16744: Fixed swagger documentation for voucher endpoints.

---

composer.json
composer.lock

Updated guzzle package version

---

.github/workflows/ci.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.yml

https://spryker.atlassian.net/browse/CC-26039

CC-26039: Add robot test

---

composer.lock

Ticket: https://spryker.atlassian.net/browse/PBC-976

PBC-976: Update spryker/oms package

---

src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-items-list/cart-items-list.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-upselling/cart-upselling.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/index.ts
src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-items-list/product-cart-items-list.twig
src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/review-average-display/review-average-display.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig

- Ticket: https://spryker.atlassian.net/browse/CC-26385

CC-26385 Optimize cart page rendering

---

src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php

Ticket: https://spryker.atlassian.net/browse/FRW-1207

FRW-1207: Integrated redirect response whitelist

---

composer.lock
src/Pyz/Zed/CompanyUser/CompanyUserDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-605
- Integration ticket: https://spryker.atlassian.net/browse/CC-27056
- Core PR: https://github.com/spryker/spryker/pull/10080
{Relevant changes for project level go here. Those will be copied to the release log for suite if necessary.}

SUPESC-605: Fix an exception on company user delete

---

.github/workflows/ci.yml
composer.json
composer.lock
config/Shared/config_default.php
src/Orm/Zed/Country/Persistence/SpyCountryStore.php
src/Orm/Zed/Country/Persistence/SpyCountryStoreQuery.php
src/Orm/Zed/Currency/Persistence/SpyCurrencyStore.php
src/Orm/Zed/Currency/Persistence/SpyCurrencyStoreQuery.php
src/Orm/Zed/Locale/Persistence/SpyLocaleStore.php
src/Orm/Zed/Locale/Persistence/SpyLocaleStoreQuery.php
src/Orm/Zed/StoreStorage/Persistence/SpyStoreListStorage.php
src/Orm/Zed/StoreStorage/Persistence/SpyStoreListStorageQuery.php
src/Orm/Zed/StoreStorage/Persistence/SpyStoreStorage.php
src/Orm/Zed/StoreStorage/Persistence/SpyStoreStorageQuery.php
src/Pyz/Client/ZedRequest/ZedRequestDependencyProvider.php
src/Pyz/Shared/SearchElasticsearch/SearchElasticsearchConfig.php
src/Pyz/Zed/PropelOrm/PropelOrmDependencyProvider.php
src/Pyz/Zed/SetupFrontend/SetupFrontendConfig.php
tests/PyzTest/Zed/Calculation/_support/CalculationBusinessTester.php
tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php

- Ticket: https://spryker.atlassian.net/browse/FRW-1203

FRW-1203 Integrated Propel changes and Symfony 6x

---

src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-28282

CC-28282 Enabled runtime events for Backend API.

---

composer.json
composer.lock
src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-26818
- Core PRs: 
- https://github.com/spryker/suite-nonsplit/pull/1846
- https://github.com/spryker/spryker/pull/7594
- https://github.com/spryker/spryker-shop/pull/791
{Relevant changes for project level go here. Those will be copied to the release log for suite if necessary.}

CC-26818 Fixed breadcrumbs for a product integration.

---

composer.lock
package-lock.json

Ticket: https://spryker.atlassian.net/browse/CC-29230

CC-29230 Remove fs dependency

---

composer.lock
src/Pyz/Zed/OauthClient/OauthClientConfig.php

- Ticket: https://spryker.atlassian.net/browse/PBC-1580
- Updates spryker/oauth-client version from 1.2.0 to 1.3.0.

PBC-1580: Updates spryker/oauth-client version to 1.3.0

---

src/Pyz/Client/MultiCart/MultiCartConfig.php

- Ticket: https://spryker.atlassian.net/browse/CC-29660

CC-29660 Fixed displaying approval statuses on shipping cart

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-27951

CC-29908 Raised date time configurator version

---

src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php

Ticket:  https://spryker.atlassian.net/browse/FRW-1791

FRW-1791 Integrated fixes for not fired kernel.terminate event in Glue.

---

composer.lock
src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-29849

CC-21301: Fixed invalid checkout payment

---

composer.json
composer.lock
src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Yves/WebProfilerWidget/WebProfilerWidgetDependencyProvider.php
src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Zed/WebProfiler/WebProfilerDependencyProvider.php

https://spryker.atlassian.net/browse/SDK-2600

SDK-2600 Added profiler module.

---

deploy.spryker-b2bintt.yml

- Ticket: https://spryker.atlassian.net/browse/CC-29960

CC-29960: Added missing mail sender.

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-29931

CC-29931 Update Sales module

---

composer.lock
src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-16486

CC-16486 Fixed the self-link for the product review resource.

---

src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.twig
src/Pyz/Yves/CartPage/Theme/default/components/organisms/cart-sidebar/cart-sidebar.twig
src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart-preview/page-layout-cart-preview.twig
src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig

- Ticket: https://spryker.atlassian.net/browse/CC-30037

CC-30037: Fixed display shopping cart items count

---

deploy.aop-b2b-testing.yml
deploy.aop-demoshop-b2b.yml
deploy.ci.acceptance.dynamic-store.yml
deploy.ci.acceptance.mariadb.dynamic-store.yml
deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.yml
deploy.ci.api.dynamic-store.yml
deploy.ci.api.mariadb.dynamic-store.yml
deploy.ci.api.mariadb.yml
deploy.ci.api.yml
deploy.ci.functional.dynamic-store.yml
deploy.ci.functional.mariadb.dynamic-store.yml
deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
deploy.ci.functional.mariadb.yml
deploy.ci.functional.yml
deploy.dev.dynamic-store.yml
deploy.dev.yml
deploy.dynamic-store.yml
deploy.yml

- Ticket: https://spryker.atlassian.net/browse/SC-15419

SC-15419 Integrated the new version of Jenkins into the all public demoshops

---

.robot/Dockerfile
codeception.functional.yml
composer.lock
src/Pyz/Zed/Application/ApplicationDependencyProvider.php
src/Pyz/Zed/Console/ConsoleDependencyProvider.php
src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Zed/Router/RouterDependencyProvider.php
tests/PyzTest/Zed/AppCatalogGui/codeception.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-5917

FRW-5917 Integrated Zed as Gateway

---

.github/workflows/ci.yml
composer.json
composer.lock
tooling.yml

- Ticket: [SDK-2359](https://spryker.atlassian.net/browse/SDK-2359)
- Update evaluator and extend evaluator configuration

SDK-2359: Update evaluator

---

src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-summary/cart-summary.twig

- Ticket: https://spryker.atlassian.net/browse/PBC-3112

PBC-3112: Fix cart page not loading CartSummaryHideTaxAmountWidget

---

.github/workflows/ci.yml

- Activate NPM checker for critical and high level vulnerabilities in CI

Activate npm checker

---

deploy.dev.yml
tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
tests/PyzTest/Yves/Application/codeception.yml
tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
tests/PyzTest/Zed/Product/Business/ProductAbstractManagerTest.php
tests/PyzTest/Zed/Product/Business/ProductConcreteManagerTest.php
tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
tests/PyzTest/Zed/ProductRelation/_support/PageObject/ProductRelationCreatePage.php
tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-780

SUPESC-780 Fixed failing automated tests on local environment.

---

deploy.aop-consultant.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-9516

APPS-9516: acp integration

---

.github/workflows/ci.yml

- Ticket: https://spryker.atlassian.net/browse/CC-31641

CC-31641 fix CI build for robot tests.

---

deploy.aop-b2b-testing.yml
deploy.aop-demoshop-b2b.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-10315

[APPS-10315] Changed mb2 gateways with domains.

---

composer.lock
package-lock.json
package.json

- Ticket: https://spryker.atlassian.net/browse/CC-31726
- Core PR: https://github.com/spryker/spryker/pull/10592

CC-31726 Update npm dependencies

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-31792
- Core PR: https://github.com/spryker/spryker/pull/10599

SUPESC-754 Fixed Shopping Lists unsharing.

---

src/Pyz/Zed/ProductManagement/Presentation/_partials/product_volume_price_action_button.twig

- Ticket: https://spryker.atlassian.net/browse/CC-31801

CC-31801 Fixed exception when setting merchant relation price.

---

deploy.aop-b2b-testing.yml
deploy.aop-consultant.yml
deploy.aop-demoshop-b2b.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-10665

[APPS-10665] Provided enpoints for TF related build.

---

src/Pyz/Zed/Sales/SalesConfig.php

- Ticket: https://spryker.atlassian.net/browse/CC-31773

CC-31773 Fixed issue with missing shipment price on Order Details page.

---

deploy.aop-b2b-testing.yml
deploy.aop-consultant.yml
deploy.aop-demoshop-b2b.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-10665

APPS-10665: Implemented endpoints for Terraform-related builds

---

config/Shared/config_default.php

- Ticket: https://spryker.atlassian.net/browse/CC-32127

 CC-32127 Cookies SameSite Lax integration.

---

src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss

Ticket: https://spryker.atlassian.net/browse/CC-30070

CC-30070 Fixed table indents.

---

composer.lock
src/Pyz/Yves/CustomerPage/CustomerPageDependencyProvider.php
src/Pyz/Yves/Security/SecurityDependencyProvider.php
src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
src/Pyz/Yves/Validator/ValidatorDependencyProvider.php
src/Pyz/Zed/Application/ApplicationDependencyProvider.php
src/Pyz/Zed/Security/SecurityDependencyProvider.php
src/Pyz/Zed/Validator/ValidatorDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-5940

FRW-5940 Updated spryker to support symfony security modules v6

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/SDK-5711

SDK-5711: Update `evaluator` dependency.

---

deploy.aop-consultant.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-2121

ACP-2121: Stripe Release fix

---

config/install/docker.ci.acceptance.dynamic-store.robot.yml
deploy.ci.acceptance.mariadb.dynamic-store.robot.yml

- Ticket: [https://spryker.atlassian.net/browse/FRW-7454]

FRW- 7454 added scheduled ci for UI Dynamic Multistore

---

.github/workflows/ci.yml
composer.lock
deploy.ci.api.mariadb.dynamic-store.robot.yml

Added new job for robot api tests dynamic multistore
- Ticket: https://spryker.atlassian.net/browse/FRW-7451

FRW - 7451 new job for robot api tests dynamic multistore

---

composer.lock

- Ticket: [https://spryker.atlassian.net/browse/CC-33122]

CC-33122 Updated composer.loc file for robot

---

composer.json
composer.lock
data/import/common/common/glossary.csv
src/Pyz/Zed/Console/ConsoleDependencyProvider.php
src/Pyz/Zed/Oms/OmsDependencyProvider.php
src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php

Tickets: 
- https://spryker.atlassian.net/browse/FRW-7452
- https://spryker.atlassian.net/browse/FRW-7291
- https://spryker.atlassian.net/browse/FRW-7432
- https://spryker.atlassian.net/browse/SUPESC-813
- https://spryker.atlassian.net/browse/SUPESC-808
- https://spryker.atlassian.net/browse/FRW-7463
- https://spryker.atlassian.net/browse/FRW-7477
- https://spryker.atlassian.net/browse/FRW-7329
- https://spryker.atlassian.net/browse/FRW-6955

FRW-6879 Integrations

---

composer.json
composer.lock

Updated composer file for product-set-gui
- Ticket: https://spryker.atlassian.net/browse/FRW-7609

FRW-7609 updated composer file

---

composer.lock
data/import/common/common/glossary.csv
deploy.dev.dynamic-store.yml
deploy.dynamic-store.yml

Tickets: 
- https://spryker.atlassian.net/browse/FRW-7821
- https://spryker.atlassian.net/browse/FRW-6380

FRW-7296 Integration

---

.github/workflows/ci.yml

- Adjusted GA configuration to enable retry for flaky tests

Adjusted GA configuration.

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-33530

CC-33530: Adjusted list of possible price dimensions.

---

src/Pyz/Zed/CommentSalesConnector/Presentation/Sales/list.twig

closes [CC-33529](https://spryker.atlassian.net/browse/CC-33529)

CC-33529: Fixed bo scroll to comment section

---

.github/workflows/.github/workflows/robot-ui-e2e-tests.yml
.github/workflows/ci.yml
.github/workflows/robot-ui-e2e-tests.yml
composer.lock
deploy.ci.acceptance.mariadb.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml

Adde new UI CI for e2e testing per each PR into master branch
- Ticket: [URL_HERE](https://spryker.atlassian.net/browse/CC-33309)

Adde new UI CI for e2e testing per each PR into master branch 

---

composer.lock
src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart-preview/page-layout-cart-preview.twig

- Ticket: https://spryker.atlassian.net/browse/CC-34110

CC-34110: Shared cart fatal error integration

---

config/install/docker.yml
deploy.aop-demoshop-b2b.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-3544

ACP-3544: Added merchant protal

---

composer.lock
src/Pyz/Yves/CartPage/Theme/default/views/product-abstract-add-to-cart-ajax/product-abstract-add-to-cart-ajax.twig
src/Pyz/Yves/CatalogPage/CatalogPageConfig.php
src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
src/Pyz/Yves/ProductWidget/Theme/default/views/catalog-product/catalog-product.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig

- Ticket: https://spryker.atlassian.net/browse/CC-13685

CC-13685: Updated product quantity and total in Mini Cart Widget from catalog AJAX add-to-cart action.

---

deploy.aop-consultant.yml

Just fixed B2B consultant deploy file.

BUGFIX: Adjusted consultant template

---

composer.lock
config/Zed/cronjobs/jenkins.php
config/Zed/navigation.xml
src/Orm/Zed/KernelApp/Persistence/SpyAppConfig.php
src/Orm/Zed/KernelApp/Persistence/SpyAppConfigQuery.php
src/Pyz/Zed/Console/ConsoleDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-8766

FRW-8766 Order matrix performance improvement integration.

---

composer.lock
src/Pyz/Zed/Console/ConsoleDependencyProvider.php
src/Pyz/Zed/CustomerAccessStorage/Persistence/Propel/Schema/spy_unauthenticated_customer_access_storage.schema.xml
src/Pyz/Zed/Event/EventConfig.php
src/Pyz/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
src/Pyz/Zed/TaxProductStorage/Persistence/Propel/Schema/spy_tax_product_storage.schema.xml

- Ticket: https://spryker.atlassian.net/browse/CC-33982
- IG ticket: https://spryker.atlassian.net/browse/CC-34373

CC-33982: P&S optimisation.

---

composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34484

CC-34484: Session locking issue after recent integration on B2C and B2C Marketplace demo shops.

---

composer.lock
deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
deploy.ci.acceptance.mariadb.dynamic-store.yml
src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-9004
- Ticket: https://spryker.atlassian.net/browse/FRW-9029

FRW-9004 Integration.

---

config/Shared/config_default.php

- Ticket: https://spryker.atlassian.net/browse/ACP-3930

ACP-3930: Changed OMS to ForeignPaymentB2CStateMachine01

---

composer.json
composer.lock
src/Pyz/Zed/DynamicEntity/DynamicEntityDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-9121

FWR-9121 Fixed broken robot test

---

src/Pyz/Zed/DynamicEntity/data/installer/configuration.json

- Ticket: https://spryker.atlassian.net/browse/FRW-8761

FRW-8761 Adjusted configuration

---

composer.lock
src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php
src/Pyz/Zed/ProductStorage/Persistence/ProductStoragePersistenceFactory.php

Tickets:
- https://spryker.atlassian.net/browse/FRW-1877
- https://spryker.atlassian.net/browse/SUPESC-866
- https://spryker.atlassian.net/browse/SUPESC-858
- https://spryker.atlassian.net/browse/FRW-9132
- https://spryker.atlassian.net/browse/FRW-8906

FRW-9030 Integrations part 5

---

composer.json
composer.lock
src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig

- Ticket: https://spryker.atlassian.net/browse/CC-34672

CC-34672 Collapsible category tree integraton

---

config/install/ci.yml
config/install/development.yml
config/install/docker.ci.acceptance.cypress.yml
config/install/docker.ci.acceptance.dynamic-store-off.cypress.yml
config/install/docker.ci.acceptance.dynamic-store-off.robot.yml
config/install/docker.ci.acceptance.dynamic-store-off.yml
config/install/docker.ci.acceptance.robot.yml
config/install/docker.ci.acceptance.yml
config/install/docker.ci.api.dynamic-store-off.yml
config/install/docker.ci.api.yml
config/install/docker.yml
config/install/testing.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-9241

FRW-9241 Adjusted installation configs.

---

config/Shared/config_default.php
src/Pyz/Zed/KernelApp/KernelAppDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/ACP-4372

ACP-4372: Fixed acp config

---

composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34730

CC-34730 Update Summernote dependency

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-20625

Integration: CC-20625

---

src/Pyz/Yves/QuickOrderPage/Theme/default/components/molecules/quick-order-row-partial/quick-order-row-partial.twig

- Ticket: https://spryker.atlassian.net/browse/ACP-4630

ACP-4427: Remove at store from network

---

deploy.aop-b2b-testing.yml
deploy.aop-demoshop-b2b.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-4378

ACP-4378: changed tenant to new format

---

deploy.aop-b2b-testing.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-4378

ACP-4378: Fixed acp url for testing build

---

composer.lock
src/Pyz/Yves/Twig/TwigDependencyProvider.php
src/Pyz/Zed/Twig/TwigDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-9287

FRW-9287 Added new twig var dumper plugin.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/SUPESC-897
- https://release.spryker.com/release/pull-request/11247

SUPESC-897 Improved performance of BundledProductTable.

---

composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34955

CC-34955 Update plotly dependency

---

composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34804

CC-34804: Exception on Manage Company Roles tests

---

composer.lock
package-lock.json
package.json
src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig

- Ticket: https://spryker.atlassian.net/browse/CC-35203

CC-35203 Adds datetimepicker js plugin

---

src/Pyz/Yves/CustomerPage/Theme/default/views/profile/profile.twig

- Ticket: https://spryker.atlassian.net/browse/FRW-10067

FRW-10067 Added CustomerEmailChangeRequestWidget widget.

---

src/Pyz/Zed/MessageBroker/MessageBrokerConfig.php
src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/ACP-4960

ACP-4690: Added missing message handler

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/FRW-9661

Integration: FRW-9661, FRW-9444, FRW-9438

---

config/Shared/config_default.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-887

SUPESC-887: integration

---

src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-filters/order-filters.twig
src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/views/quote-request-edit/quote-request-edit.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig

- Ticket: https://spryker.atlassian.net/browse/CC-35415

CC-35415: B2B yves range date picker has poor accessibility

---

src/Pyz/Yves/CommentWidget/Theme/default/components/molecules/comment-tag-form/comment-tag-form.twig

- Ticket: https://spryker.atlassian.net/browse/CC-35315

CC-35315: fixes tags for the cart's comments

---

.github/actions/job-slack-notifications/action.yml

- Ticket: https://spryker.atlassian.net/browse/CC-35773

CC-35773 Improved failed Github actions job notification.

---

tests/PyzTest/Zed/ProductOption/Business/ProductOptionFacadeAggregatorTest.php

CC-35509: trigger CI

---

.github/actions/job-slack-notifications/action.yml
.github/workflows/ci.yml
.github/workflows/robot-ui-e2e-tests.yml

- Ticket: https://spryker.atlassian.net/browse/CC-35771

CC-35509 Remove weekly CI and add run CI on commit to master.

---

composer.lock
src/Pyz/Zed/ProductManagement/ProductManagementConfig.php

Ticket: https://spryker.atlassian.net/browse/CC-35705
Release Group: https://release.spryker.com/release-groups/view/5867

CC-35705 Added search for concrete product SKU for the abstract products section in the Backoffice. 

---

tests/PyzTest/Glue/Checkout/RestApi/CompanyBusinessUnitAddressCheckoutDataRestApiCest.php

- Ticket: https://spryker.atlassian.net/browse/CC-35515

CC-35515 Fixed CompanyBusinessUnitAddressCheckoutDataRestApiCest.

---

config/install/destructive.yml

- Ticket: https://spryker.atlassian.net/browse/CC-35103
IMPORTANT: These changes should never be merged into master, only into the master-deploy branch.
- Added schedule price application and publish and sync into the destructive deployment to avoid flaky tests.

CC-35103 Added Apply Scheduled Price and P&S into destructive deployment.

---

.github/workflows/ci.yml
.github/workflows/robot-ui-e2e-tests.yml
deploy.ci.acceptance.dynamic-store-off.yml
deploy.ci.acceptance.mariadb.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.yml
deploy.ci.acceptance.mariadb.prefer-lowest.yml
deploy.ci.acceptance.mariadb.robot.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.robot.yml
deploy.ci.acceptance.yml
deploy.ci.api.dynamic-store-off.yml
deploy.ci.api.mariadb.dynamic-store-off.yml
deploy.ci.api.mariadb.robot.yml
deploy.ci.api.mariadb.yml
deploy.ci.api.yml
deploy.ci.functional.dynamic-store-off.yml
deploy.ci.functional.mariadb.dynamic-store-off.yml
deploy.ci.functional.mariadb.prefer-lowest.yml
deploy.ci.functional.mariadb.yml
deploy.ci.functional.yml

- Tickets: https://spryker.atlassian.net/browse/CC-35872, https://spryker.atlassian.net/browse/CC-35922

Enabled composer cache for CI jobs.

---

composer.json
composer.lock
src/Pyz/Zed/Event/EventDependencyProvider.php
src/Pyz/Zed/Stock/StockConfig.php

- Ticket: https://spryker.atlassian.net/browse/CC-35836
- Ticket: https://spryker.atlassian.net/browse/SUPESC-854

CC-35836: Added queue-based warehouse update functionality.

---

composer.lock
src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/service-point-shipment-types/service-point-shipment-types.twig
src/Pyz/Yves/SelfServicePortal/Theme/default/views/customer-menu-items/customer-menu-items.twig
src/Pyz/Zed/Sales/SalesDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/SSP-1263

SSP-1263 Fixed item reschedule functionality.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/FRW-10501

FRW-10501: Integration.

---

src/Orm/Zed/MerchantSalesOrder/Persistence/SpyMerchantSalesOrder.php
src/Orm/Zed/MerchantSalesOrder/Persistence/SpyMerchantSalesOrderItem.php
src/Orm/Zed/MerchantSalesOrder/Persistence/SpyMerchantSalesOrderItemQuery.php
src/Orm/Zed/MerchantSalesOrder/Persistence/SpyMerchantSalesOrderQuery.php
src/Orm/Zed/MerchantSalesOrder/Persistence/SpyMerchantSalesOrderTotals.php
src/Orm/Zed/MerchantSalesOrder/Persistence/SpyMerchantSalesOrderTotalsQuery.php
src/Orm/Zed/SelfServicePortal/Persistence/SpyProductClass.php
src/Orm/Zed/SelfServicePortal/Persistence/SpyProductClassQuery.php
src/Orm/Zed/SelfServicePortal/Persistence/SpyProductToProductClass.php
src/Orm/Zed/SelfServicePortal/Persistence/SpyProductToProductClassQuery.php
src/Orm/Zed/SelfServicePortal/Persistence/SpySalesOrderItemProductClass.php
src/Orm/Zed/SelfServicePortal/Persistence/SpySalesOrderItemProductClassQuery.php
src/Orm/Zed/SelfServicePortal/Persistence/SpySalesProductClass.php
src/Orm/Zed/SelfServicePortal/Persistence/SpySalesProductClassQuery.php
src/Pyz/Zed/Cart/CartDependencyProvider.php
src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
src/Pyz/Zed/Oms/OmsDependencyProvider.php
src/Pyz/Zed/Product/ProductDependencyProvider.php
src/Pyz/Zed/ProductStorage/ProductStorageDependencyProvider.php
src/Pyz/Zed/SelfServicePortal/Communication/Asset/Form/DataProvider/SspAssetFormDataProvider.php
src/Pyz/Zed/SelfServicePortal/Communication/SelfServicePortalCommunicationFactory.php

- Ticket: https://spryker.atlassian.net/browse/SSP-1319

SSP-1319 Fixed adding product to cart.

---

.github/workflows/ci.yml
composer.lock
deploy.ci.acceptance.mariadb.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml

Ssp master add cypress ssp env

---

data/import/common/common/glossary.csv

- Ticket: https://spryker.atlassian.net/browse/SSP-1376
- Core PR: None

SSP-1376: Update asset-related labels in glossary for clarity.

---

src/Pyz/Yves/MultiFactorAuth/Theme/default/components/molecules/multi-factor-authentication-handler/multi-factor-authentication-handler.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/index.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.twig

- Ticket: https://spryker.atlassian.net/browse/FRW-10758

FRW-10758 Fixed popup overlap with header

---

package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-36096

CC-36099: fixes security issue with node modules

---

src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig

- Ticket: https://spryker.atlassian.net/browse/FRW-10760
Updated URL handling in the `filter-category.twig`.

FRW 10760 Fixed 404 error on filter by category in dynamic sale category

---

data/import/common/common/glossary.csv

- Ticket: https://spryker.atlassian.net/browse/FRW-10781

FRW-10781 Fixed banner link to the Spryker website

---

data/import/common/common/glossary.csv
src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
src/Pyz/Yves/SalesOrderAmendmentWidget/Theme/default/components/molecules/order-amendment/order-amendment.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-sidebar-item/navigation-sidebar-item.scss

- Ticket: https://spryker.atlassian.net/browse/CC-36109

CC-36109: button layout on order details page

---

composer.lock
src/Pyz/Zed/Publisher/PublisherDependencyProvider.php

Ticket: https://spryker.atlassian.net/browse/SUPESC-789

SUPESC-789 Super attributes don't show values maintained in Backoffice.

---

composer.json
composer.lock

Ticket: https://spryker.atlassian.net/browse/CC-36115

CC-36115 Integrated bugfixes.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/FRW-10782
- Ticket: https://spryker.atlassian.net/browse/FRW-10830

FRW-10782 Upgraded MFA modules version.

---

composer.json
composer.lock

Ticket: https://spryker.atlassian.net/browse/CC-36139

CC-36139 Fixing flickery tests.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-36208

Weekly integrations.

---

.github/workflows/ci.yml
.gitignore
composer.json
composer.lock
deploy.ci.acceptance.mariadb.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
deploy.ci.acceptance.postges.dynamic-store-off.cypress.yml
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-36242

CC-36242 Update cypress-tests path

---

.github/workflows/ci.yml

- Ticket: https://spryker.atlassian.net/browse/CC-36460
- Updated CI configuration

CC-36460: Fix SSP Cypress logic

---

config/install/destructive.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-11070

Adjusted destructive
